# Generated by Django 3.2.5 on 2021-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Puzzle 3D', 'Puzzle 3D'), ('Artwall', 'Artwall'), ('Accessory', 'Accessory')], max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('width', models.DecimalField(decimal_places=3, max_digits=4)),
                ('height', models.DecimalField(decimal_places=3, max_digits=4)),
                ('depth', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('material', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
